### ISSUE TITLE
Value error on first run

### ISSUE THREAD

**Issue by gamesbook** [will8211/unimatrix#15]
Ubuntu 14.04
Python 2.7.6

After following the install and run:
```
sudo curl -L https://raw.githubusercontent.com/will8211/unimatrix/master/unimatrix.py -o /usr/local/bin/unimatrix
sudo chmod a+rx /usr/local/bin/unimatrix
unimatrix -n -s 96 -l o
```

I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/unimatrix", line 613, in <module>
    main()
  File "/usr/local/bin/unimatrix", line 608, in main
    curses.wrapper(_main)
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/bin/unimatrix", line 555, in _main
    if key.get():
  File "/usr/local/bin/unimatrix", line 407, in get
    chr_kp = chr(kp).lower()
ValueError: chr() arg not in range(0x110000)
```

**Comment by will8211** [comment]
Thanks, I'll fix that

**Comment by will8211** [comment]
Should be fixed now

**Comment by gamesbook** [comment]
All fine, thanks.
