### ISSUE TITLE
Not working on Windows 10 (Anaconda Python distribution)

### ISSUE THREAD

**Issue by AllanLRH** [will8211/unimatrix#20]
Use of another library than curses would fix it, see paragraph 5: https://docs.python.org/3.3/howto/curses.html

```
C:\Users\Adam Huxley>unimatrix -n -s 96 -l o
Traceback (most recent call last):
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\Scripts\unimatrix-script.py", line 11, in <module>
    load_entry_point('unimatrix==0.1.dev64+gcd04928', 'console_scripts', 'unimatrix')()
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 565, in load_entry_point
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2598, in load_entry_point
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2258, in load
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\site-packages\unimatrix.py", line 28, in <module>
    import curses
  File "C:\Users\Adam Huxley\Anaconda3\envs\py36\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by will8211** [comment]
Looks like you'll need to download a wheel and install the python curses package.

Go to https://www.lfd.uci.edu/~gohlke/pythonlibs/
And download either
curses‑2.2‑cp36‑cp36m‑win32.whl
curses‑2.2‑cp36‑cp36m‑win_amd64.whl
Depending on if you're running python 32 or 64 bit
Run a console, CD to the directory with the whl package, and run
```py3 -m pip install [package name]```
py3 might be a different command on your system, whatever you use to run python3

**Comment by will8211** [comment]
actually, after writing this, I realise that curses might not even work in Windows... Let me know if it works. Maybe in cygwin?

**Comment by jerry2605** [comment]
confirmed, after installed. It works in win10. 

How can I let it run in Jypyter notebook or iPython?
